# Generated by Django 2.2.5 on 2019-09-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contacts_date',
            new_name='contact_date',
        ),
    ]
